name: Discord
description: Discord Command Plugin
version: 1.01
author: Cyanade
main: me.cyanade.discord.Discord
commands:
  discord:
    description: Discord Command
  discordreload:
    description: Reload Discord Plugin Config